theme: jekyll-theme-time-machine
show_downloads: true

# google_analytics:[Your Google Analytics tracking ID]

# Name of website
title: Embedded Vehicle Mass Estimation Pipeline
description: Project for UCLA ECEM202A/CSM213A (Fall 2023)
